# Docker compose file used to run the services on production.
version: "3.8"

services:
  parser:
    build:
      context: services/parser
      dockerfile: docker/Dockerfile
    env_file:
      - services/parser/.env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/db
    restart: always

  #   app:
  #     build:
  #       context: services/app
  #       dockerfile: docker/Dockerfile.prod
  #     env_file:
  #       - services/app/.env
  #     ports:
  #       - "8000:8000"
  #     environment:
  #       - DATABASE_URL=postgresql://postgres:password@postgres:5432/db
  #     restart: always

  postgres:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_ADMIN_USER=${DB_ADMIN_USER}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
      - DB_APP_USER=${DB_APP_USER}
      - DB_APP_PASSWORD=${DB_APP_PASSWORD}
    volumes:
      - ./services/postgres/scripts:/docker-entrypoint-initdb.d/ # Run setup scripts
      - pg-data:/var/lib/postgresql/data/ # Make db data persist

volumes:
  pg-data:
