# Docker compose file used to run all services in production.
version: "3.8"

services:
  parser:
    build:
      context: services/parser
      dockerfile: docker/Dockerfile
    env_file:
      - services/parser/.env
    restart: always

  #   app:
  #     build:
  #       context: services/app
  #       dockerfile: docker/Dockerfile.prod
  #     env_file:
  #       - services/app/.env
  #     ports:
  #       - "8000:8000"
  #     environment:
  #       - DATABASE_URL=postgresql://postgres:password@postgres:5432/db
  #     restart: always
