version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        environment:
            - TEST
        env_file:
            - .env
        ports:
            - '8112:8000'
        restart: always
