version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
            # target: dev # build stage
            # args:
            #     PY_MAJOR_VERSION: ${PY_MAJOR_VERSION}
        env_file:
            - .env
        ports:
            - '8000:8000'
        restart: always
