services:
    db:
        container_name: accntu-db-test-prod
        image: postgres:16.3-alpine
        restart: always
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=db
        ports:
            - 5449:5432
        volumes:
            - pg-data:/var/lib/postgresql/data/ # Make db data persist

    app:
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/db # necessary to change since communication through container networks
        depends_on:
            - db

    parser:
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/db # necessary to change since communication through container networks
        depends_on:
            - db

volumes:
    pg-data:
