services:
    db:
        container_name: accntu-db-test-prod
        image: postgres:16.3-alpine
        restart: always
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=db
        ports:
            - 5449:5432

        volumes:
            - pg-data:/var/lib/postgresql/data/ # Make db data persist

    app:
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/db # necessary to change since communication through container networks
            - NEXT_PUBLIC_URL=http://localhost:3000
        depends_on:
            - db
        env_file:
            - ./services/app/.env
        ports:
            - 3000:3000

    parser:
        env_file:
            - ./services/parser/.env
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/db # necessary to change since communication through container networks
        depends_on:
            - db
        ports:
            - 8000:8000

volumes:
    pg-data:
