services:
    parser:
        build:
            context: ./services/parser
            dockerfile: ./docker/Dockerfile
        environment:
            - DATABASE_URL=${DATABASE_URL}
        expose:
            - 8000
        restart: always

    app:
        build:
            context: ./services/app/
            dockerfile: ./docker/Dockerfile.prod
            args:
                - DATABASE_URL=${DATABASE_URL}
                - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
                - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
                - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
        environment:
            - DATABASE_URL={DATABASE_URL}
        restart: always
        expose:
            - 3000
        command:
            - ./entrypoint.sh
