services:
    app:
        build:
            context: ./services/app/
            dockerfile: ./docker/Dockerfile.prod
            args:
                - DATABASE_URL=${DATABASE_URL}
                - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
                - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
                - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
        env_file:
            - ./services/app/.env
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/db # necessary to change since communication through container networks
        depends_on:
            - db
        restart: always
        ports:
            - 3000:3000
        command:
            - ./entrypoint.sh

    parser:
        build:
            context: ./services/parser
            dockerfile: ./docker/Dockerfile
        env_file:
            - ./services/parser/.env
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/db # necessary to change since communication through container networks
        ports:
            - '8000:8000'
        restart: always
        depends_on:
            - db

volumes:
    pg-data:
